[package]
name = "wayvrctl"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
log.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
env_logger = "0.11.8"
tokio = "1.48.0"
wayvr-ipc = { path = "../wayvr-ipc" }
shell-words = "1.1.1"
