# For how much time mouse motion events should be stopped after clicking?
# Prevents accidental dragging various GUI elements or links, making it easier to click
# Default: 300
click_freeze_time_ms: 300

# Default: true
keyboard_sound_enabled: true

# Alter default scale of various overlays
# Default: 1.0
keyboard_scale: 1.0
desktop_view_scale: 1.0
watch_scale: 1.0

# Enable / disable sliding windows back and forth with the scroll action
# Default: true
allow_sliding: true

# Enable / disable realigning the working set windows when they are shown/hidden
# Default: true
realign_on_showhide: true

# When enabled, the mouse pointer will not be moved on the screen, unless the trigger is touched
# allowing for moving both pointers off the screens to the keyboard, while keeping the cursor position
# unchanged, for when the desktop is configured to move the focus with the mouse cursor
# Default: false
focus_follows_mouse_mode: false

# Enable / disable adjusting the opacity of overlays by using the scroll action on the watch buttons
# for the screens / keyboard
# Default: true
overlay_opacity_adjustment: true
