[package]
name = "wlx-common"
version = "0.1.0"
edition = "2024"


[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
glam = { workspace = true }
chrono = "0.4.42"
idmap = { workspace = true, features = ["serde"] }
idmap-derive = { workspace = true }
