[package]
name = "wlx-common"
version = "0.1.0"
edition = "2024"


[dependencies]
serde = { workspace = true, features = ["rc"] }
glam = { workspace = true }
chrono = "0.4.42"
idmap = { workspace = true, features = ["serde"] }
idmap-derive = { workspace = true }
wayvr-ipc = { path = "../wayvr-ipc", default-features = false }
anyhow = { workspace = true }
xdg = "3.0"
log = { workspace = true }
