[package]
name = "dash-frontend"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
wgui = { path = "../wgui/" }
glam = { workspace = true, features = ["mint", "serde"] }
log.workspace = true
rust-embed.workspace = true
chrono = "0.4.42"
gio = "0.21.5"
gtk = "0.18.2"
serde.workspace = true
serde_json.workspace = true
wlx-common = { path = "../wlx-common" }
wayvr_ipc = { workspace = true }
